# Generated by Django 5.2 on 2025-04-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_statement_unique_account_date_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
