# Generated by Django 5.2 on 2025-04-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.account'),
            preserve_default=False,
        ),
    ]
