# Generated by Django 5.2 on 2025-04-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_statementitem_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['name', 'currency'], name='statements__name_c3694a_idx'),
        ),
        migrations.AddIndex(
            model_name='statementitem',
            index=models.Index(fields=['account', 'currency'], name='statements__account_0b0291_idx'),
        ),
    ]
