# Generated by Django 5.2 on 2025-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_account_statements__name_c3694a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementitem',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
